name: Auto-Merge

on:
  pull_request:
    types: [auto_merge_enabled]

permissions:
  contents: write      # Required for creating commits
  pull-requests: read  # Required for reading PR details
  issues: read        # Required for reading issue comments
  checks: read        # Required for checking status checks
  id-token: write      # Required for verified commit signing

jobs:
  helper:
    name: Helper
    environment: claude
    runs-on: ubuntu-latest
    steps:
      - name: Enhanced Auto-Merge Processing
        uses: matfax/verified-merge@main
        with:
          # Anthropic API key authentication (choose one)
          # anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude-code-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # Optional: Enable/disable Claude generation (default: true)
          enable-claude-generation: true
          
          # Optional: Timeout for waiting for status checks in seconds (default: 900 = 15 minutes)
          check-timeout-seconds: 900
          
          # Optional: Allowed conventional commit types (default: feat,fix,docs,style,refactor,perf,test,chore)
          conventional-commit-types: "feat,fix,docs,style,refactor,perf,test,chore,ci,build"
