name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.tpl'
      - '**/docs.yml'
      - '**/automerge.yml'
      - '**/action.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '**.tpl'
      - '**/docs.yml'
      - '**/automerge.yml'
      - '**/action.yml'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ## This head ref is required to enable pushes to pull request branches
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Update Action Documentation in README
        uses: matfax/action-docs@main

      - name: Commit Changes
        if: ${{ github.event_name != 'push' }}
        uses: iarekylew00t/verified-bot-commit@cc09d455be3e20eb6b1c3d1c30a5221f9475aa10 # v1
        with:
          files: '**/*.md'
          if-no-commit: notice
          message: |
            docs: update action documentation

            The documentation has been regenerated from the action.yml.

      - name: Create Pull Request
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          title: 'docs: Update action documentation'
          sign-commits: true
          signoff: true
          branch: docs/update-docs
          delete-branch: true
          labels: |
            documentation
            auto-update
          commit-message: |
            docs: update action documentation

            The documentation has been regenerated from the action.yml.
          body: |
            This pull request contains automated updates to the action README.
            
            The documentation has been regenerated from the action.yml file using the
            configured template. Please review the changes and merge if they look correct.

            Generated by: [matfax/action-docs](https://github.com/matfax/action-docs)
