name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.tpl'
      - '**/docs.yml'
      - '**/automerge.yml'
      - '**/action.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '**.tpl'
      - '**/docs.yml'
      - '**/automerge.yml'
      - '**/action.yml'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          
      - name: Update action documentation
        uses: matfax/action-docs@main
          
      - name: Create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: 'docs: auto-update action documentation'
          title: 'docs: Update action documentation'
          body: |
            This pull request automatically updates the action README based on changes to action.yml.
            
            Generated by the docs workflow.
          branch: docs/update-docs
          delete-branch: true
          sign-commits: true
          signoff: true
          labels: documentation, auto-update
